- README.md
- behat.yml.dist
- composer.json
- phpspec.yml.dist
- src/Application/MonofonyPluginTrait.php
- src/Controller/ModalController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/MonsieurBizSyliusCmsExtension.php
- src/EventListener/Admin/JavascriptBlock.php
- src/Exception/DuplicatedUiElementTypeException.php
- src/Exception/UndefinedUiElementTypeException.php
- src/Form/Type/UiElement/ImageType.php
- src/Form/Type/UiElement/QuoteType.php
- src/Form/Type/UiElement/TextType.php
- src/MonsieurBizSyliusCmsPlugin.php
- src/Resources/config/config.yaml
- src/Resources/config/routing/admin.yaml
- src/Resources/config/services.yaml
- src/Twig/CmsExtension.php
- src/UiElement/AbstractUiElement.php
- src/UiElement/Factory.php
- src/UiElement/Image.php
- src/UiElement/Quote.php
- src/UiElement/Text.php
- src/UiElement/UiElementInterface.php
- tests/Application/Kernel.php
> Rename Monsieurbiz to MonsieurBiz

- README.md
- src/Controller/ModalController.php
- src/EventListener/Admin/AppBlock.php
- src/Factory/UiElementFactory.php
- src/Factory/UiElementFactoryInterface.php
- src/Resources/config/services.yaml
- src/Twig/RichEditorExtension.php
- src/UiElement/YoutubeVideoTrait.php
- tests/RichEditorServiceProvider.php
- tests/Twig/Fixtures/rich_editor_empty_data.test
- tests/Twig/Fixtures/rich_editor_fulltext_data.legacy.test
- tests/Twig/Fixtures/rich_editor_fulltext_data.test
- tests/Twig/Fixtures/rich_editor_noelements_data.legacy.test
- tests/Twig/Fixtures/rich_editor_noelements_data.test
Improvements:
- Give the UIElement to the template via a variable `uiElement`.
- Use an interface for the `UiElementFactory` (renamed from `Factory`) and move it under the `Factory/` directory.
- Correct the twig extension tests for legacy purpose
- Add a `\MonsieurBiz\SyliusRichEditorPlugin\UiElement\YoutubeVideoTrait` trait
> Some improvements

- src/UiElement/YoutubeVideoTrait.php
I found the regex here: https://github.com/optixsolutions/youtube-url-parser/blob/master/src/UrlParser.php#L42
> Parse Youtube URLs using a regex to match all cases

- .github/workflows/recipe.yaml
- README.md
- recipe/1.0-dev/config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml
- recipe/1.0-dev/manifest.json
I've added the flex recipe for this plugin.
If this PR passes the validation we'll have to send it to the [symfony/recipes-contrib](https://github.com/symfony/recipes-contrib) repository.
> Flex recipe

- src/Form/Type/UiElement/ButtonLinkType.php
- src/Resources/views/UiElement/button_link.html.twig
- src/Resources/views/UiElement/products.html.twig
- src/Resources/views/UiElement/quote.html.twig
- src/Resources/views/UiElement/separator.html.twig
- src/Resources/views/UiElement/taxon_product.html.twig
- src/Resources/views/UiElement/text.html.twig
- src/Resources/views/UiElement/title.html.twig
- src/Resources/views/UiElement/video.html.twig
> fix crash when save without editing element and fix trads

- assets/css/app.scss
A very small change that makes the difference.
> Prevent scroll to top when opening a panel

- src/Controller/FormController.php
- src/Twig/RichEditorExtension.php
- src/Validator/Constraints/YoutubeUrlValidator.php
- Reduce cyclomatic complexity
- Update the regex to be more readable
- Reduce cyclomatic complexity of the Youtube URL Validator
- Reduce cyclomatic complexity of the data processing in form controller
> Reduce cyclomatic complexity

- UPGRADE-2.0.md
> Add a notice about removed Ui Elements into UPGRADE-2.0.md

- README.md
This is missing, and some people won't know the solution to the JS error in console
> Add instruction about assets

- UPGRADE-2.0.md
I noticed this change when updating the plugin.
> Update v2 upgrade docs

- src/Resources/config/richeditor.yaml
- src/Resources/translations/messages.en.yml
- src/Resources/translations/messages.fr.yml
- src/Resources/views/Admin/UiElement/h1.html.twig
- src/Resources/views/Admin/UiElement/h2.html.twig
- src/Resources/views/Admin/UiElement/h3.html.twig
- src/Resources/views/Shop/UiElement/h1.html.twig
- src/Resources/views/Shop/UiElement/h2.html.twig
- src/Resources/views/Shop/UiElement/h3.html.twig
> Add h1/h2/h3 elements

- src/Resources/views/Admin/app.html.twig
> Add description in Ui Element cards in Selection panel

- README.md
- UPGRADE-2.0.md
- src/Twig/RichEditorExtension.php
- tests/Application/templates/bundles/SyliusShopBundle/Product/Show/Tabs/Details/_description.html.twig
According to discussion in https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/120
We change the filter name separately
> Change Twig filter name

- src/Resources/views/Admin/app.html.twig
> Fix JS issue yelling about variable

- src/Resources/config/routing/admin.yaml
> [2.0] Remove request.isXmlHttpRequest route conditions

- src/Resources/config/routing/admin.yaml
> [1.0] Remove request.isXmlHttpRequest route condition

- src/DependencyInjection/UiElementRegistryPass.php
- src/Form/Type/UiElement/ButtonLinkType.php
- src/Resources/views/Admin/UiElement/button.html.twig
- symfony.lock
The button type can be used inside another form, and therefore inherit the options.
I want to be sure that if we use an optional button we won't be stopped by the constraints.
> Fields are not always required

- src/Form/Type/AlignmentType.php
- src/Form/Type/UiElement/ButtonLinkType.php
- src/Form/Type/UiElement/ImageType.php
- src/Form/Type/UiElement/QuoteType.php
- src/Form/Type/UiElement/TextType.php
- src/Form/Type/UiElement/TitleType.php
- src/Form/Type/UiElement/VideoType.php
- src/Form/Type/UiElement/YoutubeType.php
- src/Resources/translations/messages.en.yml
- src/Resources/translations/messages.fr.yml
- src/Resources/views/Admin/UiElement/button.html.twig
- src/Resources/views/Admin/UiElement/h1.html.twig
- src/Resources/views/Admin/UiElement/h2.html.twig
- src/Resources/views/Admin/UiElement/h3.html.twig
- src/Resources/views/Admin/UiElement/image.html.twig
- src/Resources/views/Admin/UiElement/quote.html.twig
- src/Resources/views/Admin/UiElement/text.html.twig
- src/Resources/views/Admin/UiElement/title.html.twig
- src/Resources/views/Admin/UiElement/video.html.twig
- src/Resources/views/Admin/UiElement/youtube.html.twig
- src/Resources/views/Shop/UiElement/button.html.twig
- src/Resources/views/Shop/UiElement/h1.html.twig
- src/Resources/views/Shop/UiElement/h2.html.twig
- src/Resources/views/Shop/UiElement/h3.html.twig
- src/Resources/views/Shop/UiElement/image.html.twig
- src/Resources/views/Shop/UiElement/quote.html.twig
- src/Resources/views/Shop/UiElement/text.html.twig
- src/Resources/views/Shop/UiElement/title.html.twig
- src/Resources/views/Shop/UiElement/video.html.twig
- src/Resources/views/Shop/UiElement/youtube.html.twig
> Add alignement field for some elements

- symfony.lock
- tests/Application/.gitignore
- Do not symlink the .gitignore
- Update symfony.lock
> Some craaaazy changes :p

- src/Controller/FormController.php
- src/Resources/config/services.yaml
- src/Uploader/FileUploader.php
- src/Uploader/FileUploaderInterface.php
Use interface for FileUploader to be able to customize it.
> Add FileUploaderInterface

- src/Resources/views/Admin/app.html.twig
Add paragraph button to be able to change title to paragraph
> Add paragraph button in pell editor

- .github/workflows/recipe.yaml
- .github/workflows/security.yaml
- .github/workflows/tests.yaml
- composer.json
Failing tests are fixed by #198.
> Use our own Symfony Recipes endpoint

- README.md
- dist/templates/bundles/SyliusShopBundle/Product/Show/Tabs/Details/_description.html.twig
Closes #200 
See the [preview of README](https://github.com/delyriand/SyliusRichEditorPlugin/blob/fix/update-link-example/README.md) on my branch!
And product page:
> Re-add the template in dist to display product description and update example links in README

- recipes/2.0/manifest.json
- src/Resources/config/config.yaml
- src/Resources/config/images.yaml
- src/Resources/config/richeditor.yaml
- src/Resources/config/services.yaml
- src/Resources/views/Admin/UiElement/image.html.twig
- src/Resources/views/Admin/UiElement/image_collection.html.twig
- src/Resources/views/Admin/UiElement/video.html.twig
- src/Resources/views/Form/theme.html.twig
- src/Resources/views/Shop/UiElement/image.html.twig
- src/Resources/views/Shop/UiElement/image_collection.html.twig
- src/Resources/views/Shop/UiElement/video.html.twig
- src/Twig/RichEditorExtension.php
The URL contains liip imagine filter
> Make images in image and video element use liip imagine filter

- .github/workflows/recipe.yaml
- .github/workflows/security.yaml
- .github/workflows/tests.yaml
- README.md
- Update README
- Update workflows
> Update compatibility versions

- src/Form/Type/LevelType.php
- src/Form/Type/UiElement/ButtonLinkType.php
- src/Resources/translations/messages.en.yml
- src/Resources/translations/messages.fr.yml
- src/Resources/views/Admin/UiElement/button.html.twig
- src/Resources/views/Shop/UiElement/button.html.twig
- Add level in buttons
- Link is TextType because UrlType add `https`
Then in your front you can add button variations
> Add buttons level in button element

- src/Resources/views/Admin/app.html.twig
> Correct tags display

- src/Form/Type/UiElement/AnchorType.php
- src/Form/Type/UiElement/QuoteType.php
- src/Form/Type/UiElement/SeparatorType.php
- src/Form/Type/UiElement/VideoType.php
- src/Resources/config/richeditor.yaml
- src/Resources/translations/messages.en.yml
- src/Resources/translations/messages.fr.yml
- src/Resources/views/Admin/UiElement/anchor.html.twig
- src/Resources/views/Admin/UiElement/image_collection.html.twig
- src/Resources/views/Admin/UiElement/separator.html.twig
- src/Resources/views/Admin/UiElement/video.html.twig
- src/Resources/views/Shop/UiElement/anchor.html.twig
- src/Resources/views/Shop/UiElement/image_collection.html.twig
- src/Resources/views/Shop/UiElement/separator.html.twig
- src/Resources/views/Shop/UiElement/video.html.twig
- src/WysiwygEditor/SunEditor.php
- feat(quote): quote type has minimal toolbar
- feat(separator): separator can now have thickness
- feat(video): video can manage controls and autoplay
- feat(image collection): manage dynamically image collection to 5 columns
- feat(suneditor): editor always have fullscreen, showblocs, code view
- fix(tests): Fix PHP CS tests
- feat(tags): add tags on elements
- feat(anchor): add anchor ui element
> Improve UI Elements
